### ISSUE TITLE
Feature Request - nullDefaults: Default to null when column is nullable

### ISSUE THREAD

**Issue by strongpauly** [superclaw/typeorm-stubs#1]
It would be good, as an option, to be able to stub out entities with null values unless specified.

**Comment by superclaw** [comment]
@strongpauly Good idea, thanks! Could you please add a simple description of the new option to the README file?

**Comment by strongpauly** [comment]
Done

**Comment by superclaw** [comment]
Merged, thanks. I've also added the new option to the DEFAULT_STUB_OPTIONS const.
